Tested unitaries for SDNW, RDNW, SDWS, RDWS
QuCoNot/QuCoNot pull request #38
Opened 2023-11-06 10:45 UTC by HandyKurniawan

added 4 classes

2023-11-06 11:10 UTC, adamglos92 commented on tests/test_unitary_rdws.py
> +    def _take_matrix(self):
This example in turn is non-wasting, because you have identity on auxiliary system

2023-11-06 22:01 UTC, HandyKurniawan commented on tests/test_unitary_base.py
> +    @abstractmethod
ok great

2023-11-06 22:02 UTC, HandyKurniawan commented on tests/test_unitary_base.py
> +        return U
ok

2023-11-06 22:07 UTC, HandyKurniawan commented on tests/test_unitary_rdnw.py
> +    def _take_matrix(self):
ah i think i missed the graph. i didn't put them to be not passing.

2023-11-16 23:18 UTC, HandyKurniawan commented
also fix #29 #30 #32

2023-11-19 20:40 UTC, adamglos92 requested changes
One general comments:
* [x] To avoid redundancy, you could make a two helping functions that will generate the sum_i V_i you use for clean and sum_i W_i for wasted.
* [x] it would be better if V_i and W_i would be different matrices (which would be quite easy to do so if you would write two seperate functions)

2023-11-19 20:40 UTC, adamglos92 commented on tests/test_unitary_rcwe.py
> +    _controls_no_list: List[int] = [0]
```suggestion
    _controls_no_list: List[int] = [0, 1]
```
there are two cases in here

2023-11-19 20:40 UTC, adamglos92 commented on tests/test_unitary_rdws.py
> +        V = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [1 / np.sqrt(2), -1 * 1 / np.sqrt(2)]])
```suggestion
        V = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [1 / np.sqrt(2), -1 / np.sqrt(2)]])
```

2023-11-19 20:40 UTC, adamglos92 commented on tests/test_unitary_sdws.py
> +        V = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [1 / np.sqrt(2), -1 * 1 / np.sqrt(2)]])
```suggestion
        V = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [1 / np.sqrt(2), 1 / np.sqrt(2)]])
```

2023-11-19 21:33 UTC, HandyKurniawan commented on tests/test_unitary_sdws.py
> +        V = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [1 / np.sqrt(2), -1 * 1 / np.sqrt(2)]])
Thanks!

2023-11-19 21:33 UTC, HandyKurniawan commented on tests/test_unitary_rdws.py
> +        V = np.array([[1 / np.sqrt(2), 1 / np.sqrt(2)], [1 / np.sqrt(2), -1 * 1 / np.sqrt(2)]])
Thanks!

2023-11-19 21:36 UTC, HandyKurniawan commented on tests/test_unitary_rcwe.py
> +    _controls_no_list: List[int] = [0]
yes, i forgot to open them.

2023-11-20 13:46 UTC, adamglos92 approved these changes

2023-11-20 13:51 UTC, merged